let songsData = [
  {
    id: "0",
    songName: "8 Raflaan",
    filePath: "songs/8 Raflaan.mp3",
    coverPath: "covers/8-Raflaan cover.jpg",
    timestamp: "2:10",
  },
  {
    id: "1",
    songName: "295",
    filePath: "songs/295.mp3",
    coverPath: "covers/295-cover.jpg",
    timestamp: "4:30",
  },
  {
    id: "2",
    songName: "Admiring You",
    filePath: "songs/Admiring You.mp3",
    coverPath: "covers/admiring you cover.jpg",
    timestamp: "3:34",
  },
  {
    id: "3",
    songName: "Arjan Vailly Ne",
    filePath: "songs/Arjan Vailly Ne.mp3",
    coverPath: "covers/arjan vaieley cover.jpg",
    timestamp: "3:02",
  },
  {
    id: "4",
    songName: "Badnam",
    filePath: "songs/Badnam.mp3",
    coverPath: "covers/badnaam cover.jpg",
    timestamp: "3:23",
  },
  {
    id: "5",
    songName: "Baller",
    filePath: "songs/Baller.mp3",
    coverPath: "covers/baller cover.jpg",
    timestamp: "2:28",
  },
  {
    id: "6",
    songName: "Bilionera",
    filePath: "songs/Bilionera.mp3",
    coverPath: "covers/billionera-cover.jpg",
    timestamp: "3:05",
  },
  {
    id: "7",
    songName: "Born To Shine",
    filePath: "songs/Born To Shine.mp3",
    coverPath: "covers/born to shine cover.jpg",
    timestamp: "3:33",
  },
  {
    id: "8",
    songName: "Chaleya",
    filePath: "songs/Chaleya.mp3",
    coverPath: "covers/chaleya-cover.jpg",
    timestamp: "3:20",
  },
  {
    id: "9",
    songName: "Cheap-Thrills",
    filePath: "songs/Cheap-Thrills.mp3",
    coverPath: "covers/cheap thrills-cover.jpg",
    timestamp: "3:31",
  },
  {
    id: "10",
    songName: "Check-It-Out",
    filePath: "songs/Check-It-Out.mp3",
    coverPath: "covers/check it out-cover.jpg",
    timestamp: "3:15",
  },
  {
    id: "11",
    songName: "Cheques",
    filePath: "songs/Cheques.mp3",
    coverPath: "covers/cheques-cover.jpg",
    timestamp: "3:03",
  },
  {
    id: "12",
    songName: "Daku",
    filePath: "songs/Daku.mp3",
    coverPath: "covers/daku-cover.jpg",
    timestamp: "2:11",
  },
  {
    id: "13",
    songName: "Desperado",
    filePath: "songs/Desperado.mp3",
    coverPath: "covers/desperado-cover.jpg",
    timestamp: "4:23",
  },
  {
    id: "14",
    songName: "Dhundhla",
    filePath: "songs/Dhundhla.mp3",
    coverPath: "covers/dhundhla cover.jpg",
    timestamp: "3:02",
  },
  {
    id: "15",
    songName: "Diamond",
    filePath: "songs/Diamond.mp3",
    coverPath: "covers/diamond cover.jpg",
    timestamp: "4:00",
  },
  {
    id: "16",
    songName: "Dilawara",
    filePath: "songs/Dilawara.mp3",
    coverPath: "covers/dilawara-cover.jpg",
    timestamp: "3:42",
  },
  {
    id: "17",
    songName: "Do You Know",
    filePath: "songs/Do-You-Know.mp3",
    coverPath: "covers/do you know cover.jpg",
    timestamp: "3:39",
  },
  {
    id: "18",
    songName: "Gaal Ni Kadni",
    filePath: "songs/Gaal-Ni-Kadni.mp3",
    coverPath: "covers/gaal ni kadni cover.jpg",
    timestamp: "4:13",
  },
  {
    id: "19",
    songName: "Gaddi Kaali",
    filePath: "songs/Gaddi Kaali.mp3",
    coverPath: "covers/gaddi kaali cover.jpg",
    timestamp: "3:08",
  },
  {
    id: "20",
    songName: "Gasolina",
    filePath: "songs/Gasolina.mp3",
    coverPath: "covers/gasolina-cover.jpg",
    timestamp: "3:12",
  },
  {
    id: "21",
    songName: "Guitar Sikhda",
    filePath: "songs/Guitar Sikhda.mp3",
    coverPath: "covers/guitar sikhda cover.jpg",
    timestamp: "3:09",
  },
  {
    id: "22",
    songName: "Hass Hass",
    filePath: "songs/Hass Hass.mp3",
    coverPath: "covers/hass hass cover.jpg",
    timestamp: "2:32",
  },
  {
    id: "23",
    songName: "Heeriye",
    filePath: "songs/Heeriye.mp3",
    coverPath: "covers/heeriye cover.jpg",
    timestamp: "3:14",
  },
  {
    id: "24",
    songName: "Jaadugar",
    filePath: "songs/Jaadugar.mp3",
    coverPath: "covers/jaadugar cover.jpg",
    timestamp: "3:12",
  },
  {
    id: "25",
    songName: "Jai Hind Ki Senaa",
    filePath: "songs/Jai Hind Ki Senaa.mp3",
    coverPath: "covers/jai hind ki sena-cover.jpg",
    timestamp: "2:31",
  },
  {
    id: "26",
    songName: "Janiye",
    filePath: "songs/Janiye.mp3",
    coverPath: "covers/janiye-cover.jpg",
    timestamp: "3:43",
  },
  {
    id: "27",
    songName: "Judge",
    filePath: "songs/Judge.mp3",
    coverPath: "covers/judge cover.jpg",
    timestamp: "3:01",
  },
  {
    id: "28",
    songName: "Kahani Suno",
    filePath: "songs/Kahani Suno.mp3",
    coverPath: "covers/kahani suno-cover.jpg",
    timestamp: "2:53",
  },
  {
    id: "29",
    songName: "Kinni Kinni",
    filePath: "songs/Kinni Kinni.mp3",
    coverPath: "covers/kinni kinni cover.jpg",
    timestamp: "3:31",
  },
  {
    id: "30",
    songName: "Mi Amor",
    filePath: "songs/Mi-Amor.mp3",
    coverPath: "covers/mi amor-cover.jpg",
    timestamp: "3:23",
  },
  {
    id: "31",
    songName: "Moon Rise",
    filePath: "songs/Moon Rise.mp3",
    coverPath: "covers/moon rise-cover.jpg",
    timestamp: "2:54",
  },
  {
    id: "32",
    songName: "Nakhre",
    filePath: "songs/Nakhre.mp3",
    coverPath: "covers/nakhre cover.jpg",
    timestamp: "3:29",
  },
  {
    id: "33",
    songName: "No Reason",
    filePath: "songs/No Reason.mp3",
    coverPath: "covers/no reason cover.jpg",
    timestamp: "3:38",
  },
  {
    id: "34",
    songName: "O Mahi",
    filePath: "songs/O Mahi.mp3",
    coverPath: "covers/o mahi cover.jpg",
    timestamp: "3:53",
  },
  {
    id: "35",
    songName: "Obsessed",
    filePath: "songs/Obsessed.mp3",
    coverPath: "covers/obsessed-cover.jpg",
    timestamp: "3:10",
  },
  {
    id: "36",
    songName: "OG",
    filePath: "songs/OG.mp3",
    coverPath: "covers/og-cover.jpg",
    timestamp: "3:17",
  },
  {
    id: "37",
    songName: "One Love",
    filePath: "songs/One Love.mp3",
    coverPath: "covers/one love-cover.jpg",
    timestamp: "2:39",
  },
  {
    id: "38",
    songName: "Pehle Bhi Main",
    filePath: "songs/Pehle Bhi Main.mp3",
    coverPath: "covers/pejhle bhi main cover.jpg",
    timestamp: "4:10",
  },
  {
    id: "39",
    songName: "Ram Ram",
    filePath: "songs/Ram Ram.mp3",
    coverPath: "covers/ram ram cover.jpg",
    timestamp: "3:41",
  },
  {
    id: "40",
    songName: "Rao Sahab Drill",
    filePath: "songs/Rao Sahab Drill.mp3",
    coverPath: "covers/rao sahab drill-cover.jpg",
    timestamp: "3:31",
  },
  {
    id: "41",
    songName: "Rubicon Drill",
    filePath: "songs/Rubicon Drill.mp3",
    coverPath: "covers/rubicon drill cover.jpg",
    timestamp: "3:08",
  },
  {
    id: "42",
    songName: "Shada",
    filePath: "songs/Shada.mp3",
    coverPath: "covers/shada cover.jpg",
    timestamp: "3:58",
  },
  {
    id: "43",
    songName: "Shadgi",
    filePath: "songs/Shadgi.mp3",
    coverPath: "covers/shadgi cover.jpg",
    timestamp: "3:12",
  },
  {
    id: "44",
    songName: "Shoorveer-Shivaji",
    filePath: "songs/Shoorveer-Shivaji.mp3",
    coverPath: "covers/shoorveer shivaji-cover.jpeg",
    timestamp: "3:33",
  },
  {
    id: "45",
    songName: "Softly",
    filePath: "songs/Softly.mp3",
    coverPath: "covers/softly cover.jpg",
    timestamp: "2:35",
  },
  {
    id: "46",
    songName: "Still Rollin",
    filePath: "songs/Still Rollin.mp3",
    coverPath: "covers/still rollin-cover.jpg",
    timestamp: "2:54",
  },
  {
    id: "47",
    songName: "Tu Hai Kahan",
    filePath: "songs/Tu Hai Kahan.mp3",
    coverPath: "covers/tu hai kahan cover.jpg",
    timestamp: "4:23",
  },
  {
    id: "48",
    songName: "Vail",
    filePath: "songs/Vail.mp3",
    coverPath: "covers/vail cover.jpg",
    timestamp: "3:21",
  },
  {
    id: "49",
    songName: "White Brown Black",
    filePath: "songs/White Brown Black.mp3",
    coverPath: "covers/white brown black-cover.jpg",
    timestamp: "2:56",
  },
];
export default songsData;
